version: '3.3'

services:
  sync:
    build: .
    image: 0g-scan:latest
    command: sync
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env

  stat:
    image: 0g-scan:latest
    command: stat
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env

  api:
    image: 0g-scan:latest
    command: api
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env

  da_api:
    image: 0g-scan:latest
    command: da_api
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
