version: '3.3'

services:
  sync:
    build: .
    image: 0g-scan:latest
    command: sync
    restart: unless-stopped
    environment:
      - 0G_SCAN_LOG_LEVEL=info
    network_mode: host
  #    container_name: 0g-scan-sync

  stat:
    image: 0g-scan:latest
    command: stat
    restart: unless-stopped
    environment:
      - 0G_SCAN_LOG_LEVEL=info
    network_mode: host
  #    container_name: 0g-scan-stat

  api:
    image: 0g-scan:latest
    command: api
    restart: unless-stopped
    environment:
      - 0G_SCAN_LOG_LEVEL=info
      - 0G_SCAN_API_ENDPOINT=:${API_LISTEN_PORT:-16451}
    network_mode: host
  #    container_name: 0g-scan-api

  da_api:
    image: 0g-scan:latest
    command: da_api
    restart: unless-stopped
    environment:
      - 0G_SCAN_LOG_LEVEL=info
      - 0G_SCAN_API_ENDPOINT=:${API_LISTEN_PORT:-17651}
    network_mode: host
#    container_name: 0g-scan-da-api
